name=32chInput
version=1.0.0
author=krzychopcb.pl
maintainer=Krzych <fajnysoft@gmail.com>
sentence=Arduino library for 32chinput
category=Inputs & Outputs
url=https://github.com/krzychoooo/32chInput.git
architectures=*